fix regex
MTI830PyTraders/twitterSentiments pull request #2
Opened 2018-06-10 03:50 UTC by benoxoft

2018-06-10 15:54 UTC, mikefaille commented
LGTM

2018-06-10 15:54 UTC, mikefaille requested changes

2018-06-10 15:54 UTC, mikefaille commented on clean.py
>      # (https?://(?:[-\w.]|(?:%[\da-fA-F]{2}))+) : remove urls starting with 'http(s)'
Just update this comment please

2018-06-11 22:11 UTC, benoxoft commented
@mikefaille fixed

2018-06-12 00:47 UTC, ttauveron approved these changes
LGTM

2018-06-12 00:47 UTC, mikefaille approved these changes
lgtm

2018-06-12 00:47 UTC, merged