Yahoo Finance downloader
MTI830PyTraders/twitterSentiments pull request #3
Opened 2018-06-10 06:08 UTC by ttauveron

2018-06-10 15:51 UTC, mikefaille commented
Cool

2018-06-10 15:52 UTC, mikefaille commented
LGTM

2018-06-10 15:53 UTC, mikefaille approved these changes

2018-06-11 22:39 UTC, benoxoft requested changes
I'd remove the .idea folder and add it to .gitignore

2018-06-12 04:23 UTC, benoxoft approved these changes

2018-06-12 04:23 UTC, merged